import 'dart:io';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../../models/floor_plan_model.dart';
import '../../../models/staff_model.dart';
import '../../../models/room_model.dart';

class MapService {
  final FirebaseStorage _storage = FirebaseStorage.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // Upload Floor Plan Image to Storage and Save Metadata to Firestore
  Future<void> uploadFloorPlan({
    required String hotelId,
    required String floorName,
    required File imageFile,
    required List<String> exitCoordinates,
    required List<String> stairwellCoordinates,
    required List<String> assemblyPoints,
  }) async {
    try {
      // 1. Generate unique file name
      String fileName = '${DateTime.now().millisecondsSinceEpoch}_$floorName.png';
      Reference ref = _storage.ref().child('hotels/$hotelId/floor_plans/$fileName');

      // 2. Upload image to Firebase Storage
      UploadTask uploadTask = ref.putFile(imageFile);
      TaskSnapshot snapshot = await uploadTask;
      
      // 3. Get the download URL
      String downloadUrl = await snapshot.ref.getDownloadURL();

      // 4. Create FloorPlanModel instance
      FloorPlanModel newFloorPlan = FloorPlanModel(
        id: '', // Will be generated by Firestore
        floorName: floorName,
        imageUrl: downloadUrl,
        exitCoordinates: exitCoordinates,
        stairwellCoordinates: stairwellCoordinates,
        assemblyPoints: assemblyPoints,
      );

      // 5. Save to Firestore under /hotels/{hotelId}/floorPlans
      await _firestore
          .collection('hotels')
          .doc(hotelId)
          .collection('floorPlans')
          .add(newFloorPlan.toMap());
          
    } catch (e) {
      throw Exception('Failed to upload floor plan: $e');
    }
  }

  // Fetch all floor plans for a specific hotel
  Stream<List<FloorPlanModel>> getFloorPlans(String hotelId) {
    return _firestore
        .collection('hotels')
        .doc(hotelId)
        .collection('floorPlans')
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => FloorPlanModel.fromMap(doc.data(), doc.id))
            .toList());
  }

  // Real-time Staff Tracking: Stream staff locations filtered by role/zone if necessary
  Stream<List<StaffModel>> getStaffLocations() {
    return _firestore
        .collection('staff')
        .where('isActive', isEqualTo: true)
        // Optionally add where('lastLocationUpdate', isGreaterThan: DateTime.now().subtract(Duration(minutes: 5)))
        // to filter out stale locations
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => StaffModel.fromMap(doc.data(), doc.id))
            .toList());
  }

  // Update current user's location on the map
  Future<void> updateStaffLocation(String uid, String floorId, double x, double y) async {
    try {
      await _firestore.collection('staff').doc(uid).update({
        'lastKnownLocation': {
          'floorId': floorId,
          'x': x,
          'y': y,
        },
        'lastLocationUpdate': FieldValue.serverTimestamp(),
      });
    } catch (e) {
      print('Failed to update location: $e');
    }
  }

  // Fetch all rooms for a specific hotel/floor
  Stream<List<RoomModel>> getRooms(String hotelId) {
    return _firestore
        .collection('hotels')
        .doc(hotelId)
        .collection('rooms')
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => RoomModel.fromMap(doc.data(), doc.id))
            .toList());
  }

  // Update room clearance status
  Future<void> updateRoomClearanceStatus(String hotelId, String roomId, String status) async {
    try {
      await _firestore
          .collection('hotels')
          .doc(hotelId)
          .collection('rooms')
          .doc(roomId)
          .update({
        'clearanceStatus': status,
        'lastClearanceUpdate': FieldValue.serverTimestamp(),
      });
    } catch (e) {
      throw Exception('Failed to update room status: $e');
    }
  }
}

